[package]
name = "gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
bedrock = { git = "https://github.com/bedrock-crustaceans/bedrock-rs", features = ["full", "protocol-all", "protocol-dyn-name"] }
tracing = "0.1.44"
egui = "0.34.1"
egui_material_icons = "0.6.0"
eframe = "0.34.1"
crossbeam = "0.8.4"
tokio = "1.52.1"
chrono = "0.4.44"